require "plugins.configs.treesitter"
require "plugins.configs.mason"
require "plugins.configs.lsp"
require "plugins.configs.server_settings"
require "plugins.configs.cmp"
require "plugins.configs.nvim-tree"
require "plugins.configs.lualine"
require "plugins.configs.bufferline"
